prometheus:
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  adminPassword: prom-operator
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      url: http://loki.monitoring:3100
      access: proxy
      isDefault: false
    - name: Jaeger
      type: jaeger
      uid: jaeger
      url: http://jaeger.monitoring:16686
      access: proxy
      isDefault: false

alertmanager:
  enabled: false

nodeExporter:
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      memory: 64Mi
