apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://kiali.org/helm-charts
      chart: kiali-server
      targetRevision: 2.27.0
      helm:
        releaseName: kiali
        valueFiles:
          - $values/helm/kiali/values.yaml
    - repoURL: https://github.com/Vivid-Vortex-DevOps/local-platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
