apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/Vivid-Vortex-DevOps/local-platform-infra.git
    targetRevision: main
    path: helm/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
