---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: go-crud-db-credentials
  namespace: applications-dev
spec:
  encryptedData:
    database-url: AgCEXZ1RTzu3XS5gnwssG5b5TAvUNXcPbugtJPit4Isz6H5HfztlXO0+3cr/a210B4JZrkC2d1pcHUCRJiID0i8NMmegwbnOXNJSZ1IbhXDw+Ud6nu9jTvcYW0fFiAqYglekXFGdEigZYDSGQyU4/pUgu5aBpMqjNJNYOAnDnnPCs4rV0cQl8TLUU2vyO+SpHgKEE4fqireE+mdtqX6g3BXXXMgE4uHmhWfzwLdZvrWRzMsF4uaX4FEhGwL8T1ywDouFOAlWGo5gw8/WIaxS4B7XhKryWQ1hzlNSL/ujo6IE/zElJb1Lc0fcQWo+oekJAORiCRcRycxRwQJde9tr376Mj8KH7sVk2uDnlaAN+MY9f9FpjlZTuSHQZL2KOPuM5rSkMq8+XpRgV3sVJD0tTBeb/IkikfGej7XIHMDn0RnykFYOhHj8LckVfetrY6JvEgdJZ/pxtY4R+TDS2O2YcSwQpHdrhS8BbwhLZHc/uVfZSWlg9LvaABQA1s9Isa06g1E816OjoS7RhfBYhOGjHdYMb/MOki8PLXRwHjDyTQ/0Xl5NEzKT+NBCm0ITHH1fu1IKLEavBK0W/aheZxM4fhXVGiWlXfMsuI+SlxUWipEDX7fDlOY14hCKSnMU2LPZo0hP69WHhxMSEapVYXM8uP5odb5+PUjvn81yBq0fVS2yAgRDNXJP8/f474EhrW7JoUavSqqzbF68KUqtKR397TXq+rbJPJfgS+YLG2DjwjyQEuU9B7Uk6QUZO1CYt+uqSju00uZdxsGOf3kV8aghPzUqOKTrxELQU3PH14u8WXIlVim1sKt9AxdW/FS5W3oxO70VObfCRYRzGN0e1zf6
  template:
    metadata:
      creationTimestamp: null
      name: go-crud-db-credentials
      namespace: applications-dev
